apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: default
spec: 
  storageClassName: storage1-class
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi