apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: pappu-class
provisioner: file.csi.azure.com
parameters:
  resourceGroup: rgtoday
  storageAccount: storagetoday1
  secretName: azure-secret
reclaimPolicy: Retain
